### ISSUE TITLE
Gulp 4 issue

### ISSUE THREAD

**Issue by dhano6** [HackerThemes/theme-kit#10]
It looks like the gulpfile is not working anymore with gulp 4. I'm getting the AssertionError [ERR_ASSERTION]: Task function must be specified and it looks like the syntax for executing more tasks in series has changed. 
https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-tasks-in-series.md
Any chance it will be updated for your gulpfile? Thanks

**Comment by arechsteiner** [comment]
`npm install` should install the correct gulp version (3.9), are you using this in a bigger context where you need gulp 4?

I'll update it to gulp 4 at some point but probably not today or tomorrow.

**Comment by arechsteiner** [comment]
Alright this should now work with gulp 4. Could you try and confirm that it works when convenient?

**Comment by dhano6** [comment]
It works fine now. Thank you
