### ISSUE TITLE
Error message when playing with custom variables

### ISSUE THREAD

**Issue by HillbillyGeek** [HackerThemes/theme-kit#4]
Newbie with out of the box Mac install : I get the following error message in Terminal from gulp watch:
`Error in plugin 'sass'
Message:
    scss/mytheme.scss
Error: It's not clear which file to import for '@import "../node_modules/bootstrap/scss/bootstrap"'.
       Candidates:
         ../node_modules/bootstrap/scss/bootstrap.scss
         ../node_modules/bootstrap/scss/bootstrap.css
       Please delete or rename all but one of these files.
        on line 7 of scss/mytheme.scss
>> @import '../node_modules/bootstrap/scss/bootstrap';`

**Comment by arechsteiner** [comment]
The file `node_modules/bootstrap/scss/bootstrap.css` shouldn't really exists. Did you maybe run the sass compiler there?

You could either delete it or specify the import by adding the .scss file ending.
